Resources:
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Origins:
          - Id: AppOrigin
            DomainName: !Select [1, !Split ['//', !GetAtt AppBucket.WebsiteURL]] # removes the http:// part
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: http-only # Do I need https-only?
        DefaultCacheBehavior:
          TargetOriginId: AppOrigin
          ForwardedValues:
            QueryString: true
          ViewerProtocolPolicy: redirect-to-https
          # MinTTL: 0
        DefaultRootObject: index.html
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
        Aliases: !If
          - HasCloudFrontDnsAlias
          - - ${self:custom.domainName}
          - !Ref AWS::NoValue
        ViewerCertificate: !If
          - HasCloudFrontDnsAlias
          - AcmCertificateArn: ${self:custom.certificateArn}
            SslSupportMethod: sni-only
            # MinimumProtocolVersion: _ # I didn't set this, it defaulted to TLSv1
          - CloudFrontDefaultCertificate: true
