Resources:
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: ${self:service}-user-pool-${sls:stage}
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: true
        # InviteMessageTemplate: _
      AliasAttributes:
        - preferred_username
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: ${self:service}-user-pool-client-${sls:stage}
      UserPoolId: !Ref CognitoUserPool
      ExplicitAuthFlows:
        - USER_PASSWORD_AUTH
      # AccessTokenValidity: 5
      # IdTokenValidity: 5
      GenerateSecret: false

Outputs:
  CognitoUserPoolClientId:
    Value: !Ref CognitoUserPoolClient
