Resources:
  AppBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:custom.appBucketName}
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: false # was needed to allow Serverless to deploy the bucket policy resource
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html
        # ErrorDocument: error.html

  AppAccessPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref AppBucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action:
              - s3:GetObject
            Resource: arn:aws:s3:::${self:custom.appBucketName}/*

Outputs:
  AppBucketName:
    Value: !Ref AppBucket
  AppBucketWebsiteURL:
    Value: !GetAtt AppBucket.WebsiteURL
