Resources:
  AppBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:custom.appBucketName}
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
  # TODO: Do I need a policy?
  # AppAccessPolicy:
  #   Type: AWS::S3::BucketPolicy
  #   Properties:
  #     Bucket:
  #       Ref: AppBucket
  #     PolicyDocument:
  #       Statement:
  #         - Sid: PublicReadGetObject
  #           Effect: Allow
  #           Principal: "*"
  #           Action:
  #             - s3:GetObject
  #           Resource: arn:aws:s3:::${self:custom.appBucketName}/*
