service: cloudaxes
frameworkVersion: '3'
useDotenv: true

custom:
  serverlessPluginTypescript:
    tsConfigFileLocation: tsconfig.build.json

  appBucketName: ${self:service}-app-${sls:stage}
  s3Sync:
    - bucketName: ${self:custom.appBucketName}
      localDir: ../client/dist

  certificateArn: ${env:ACM_CERTIFICATE_ARN, ''}
  domainName: ${env:DOMAIN_NAME, ''}

provider:
  name: aws
  runtime: nodejs18.x
  timeout: 15 # default is 6
  profile: ${opt:aws-profile, env:AWS_PROFILE, 'default'}
  region: ${opt:region, env:REGION}
  environment:
    NODE_ENV: ${env:NODE_ENV, 'development'}
    REGION: ${aws:region}
  httpApi:
    cors: true
    authorizers:
      jwtCognitoAuthorizer:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl: !GetAtt CognitoUserPool.ProviderURL
        audience:
          - !Ref CognitoUserPoolClient

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - ec2:DescribeInstances
          Resource: '*'

functions:
  trpc:
    name: ${self:service}-trpc-${sls:stage}
    handler: src/index.handler
    events:
      - httpApi:
          method: GET
          path: /trpc/{proxy+}
          authorizer:
            name: jwtCognitoAuthorizer
      - httpApi:
          method: POST
          path: /trpc/{proxy+}
          authorizer:
            name: jwtCognitoAuthorizer

resources:
  - Conditions:
      HasCloudFrontDnsAlias: !Not
        - !Equals
          - ${self:custom.certificateArn, ''}
          - ''
  - ${file(resources/cognito_user_pool.yml)}
  - ${file(resources/s3.yml)}
  - ${file(resources/cloudfront.yml)}

plugins:
  - serverless-s3-sync
  - serverless-plugin-typescript
  - serverless-tscpaths
  - serverless-offline
